pipeline {
    agent {
        docker {
            image 'node:14' // Use the official Node.js image with version 14.x
            args '-p 3000:3000' // If your React app is running on port 3000
        }
    }

    stages {
        stage('Checkout') {
            steps {
                // Check out your repository
                checkout scm
            }
        }

        stage('Build') {
            steps {
                // Install dependencies and build the React app
                sh 'cd frontend/recipe-frontend && npm install && npm run build'
            }
        }

        stage('Test') {
            steps {
                // Run tests if you have any
                sh 'cd frontend/recipe-frontend && npm test'
            }
        }

    }     
}
